c関数を編集

diff --git a/zsh/functions/c b/zsh/functions/c
--- a/zsh/functions/c
+++ b/zsh/functions/c
@@ -1,18 +1,28 @@
 c() {
     time_opt=""
     include_compile=0
+    cc_flags=()
 
     while [[ "$1" == -* ]]; do
         case "$1" in
             -p|-v) time_opt="$1"; shift ;;
             -f) time_opt="-f"; format="$2"; shift 2 ;;
             -T) include_compile=1; shift ;;
+            -D|-I)
+                [[ -n "$2" ]] || { echo "missing arg for $1"; return 1; }
+                cc_flags+=("$1$2")
+                shift 2
+                ;;
+            -D*|-I*|-O*|-W*|-std=*|-march=*|-mtune=*|-g|-ggdb|-fsanitize=*|-fno-*|-pthread)
+                cc_flags+=("$1")
+                shift
+                ;;
             --) shift; break ;;
             *) break ;;
         esac
     done
 
-    [[ "$1" == *.c ]] || { echo "Usage: c [-p|-v|-f FORMAT|-T] file.c [args...]"; return 1; }
+    [[ "$1" == *.c ]] || { echo "Usage: c [-p|-v|-f FORMAT|-T] [-D...|-I...|-O...] file.c [args...]"; return 1; }
 
     src="$(realpath "$1")"
     shift
@@ -24,9 +34,9 @@ c() {
     out="$build_dir/$name"
 
     if grep -q '#[[:space:]]*include[[:space:]]*<math\.h>' "$src"; then
-        compile_cmd="cc \"$src\" -o \"$out\" -lm"
+        compile_cmd="cc ${cc_flags:+${(j: :)cc_flags}} \"$src\" -o \"$out\" -lm"
     else
-        compile_cmd="cc \"$src\" -o \"$out\""
+        compile_cmd="cc ${cc_flags:+${(j: :)cc_flags}} \"$src\" -o \"$out\""
     fi
 
     if [[ "$OSTYPE" == "darwin"* && "$time_opt" == "-v" ]]; then
